### ISSUE TITLE
Do correlated timeseries bias the PMF or only the uncertainty estimates?

### ISSUE THREAD

**Issue by John-Jumper** [choderalab/pymbar#208]
The documentation for MBAR strenuously points out the need for uncorrelated input configurations.  I am only interested in unbiased estimates of observables for many simulations and do not need to measure uncertainties (these are handled in another part of my procedure).  Will correlated data bias expectation values and observables?  If it does bias observables, am I okay as long as the correlation time is the roughly the same for all thermodynamic states?

Best,
John Jumper

**Comment by mrshirts** [comment]
As long as you have good uncertainties somewhere (like boostrapping), then correlated data will not bias the expectations PROVIDED you are decorrelating over time.  If you discover the correlation time is 50% of your simulation, you probably haven't visited all of the relevant states, and you will have bias simply because of lack of sampling.  So I certainly would suggest looking at the autocorrelation time just to be sure.

**Comment by jchodera** [comment]
Our experience has been that using correlated data to compute expectations
does not lead to significant bias, though it can be much slower than using
uncorrelated data.

**Comment by John-Jumper** [comment]
Great, thanks.  I have good control over statistical uncertainty later in the pipeline, although I will definitely have to monitor equilibration.
