### ISSUE TITLE
Warning: Should have \sum_k N_k W_nk = 1.  Actual sum of row 0 was 0.000000

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#223]
`pymbar 3.0.0.beta2` seems to have unstable variance computation issues:

CC: https://github.com/choderalab/simulation-health-reports/issues/1

`pymbar-2.1beta0` doesn't have this issue.

**Comment by Lnaden** [comment]
Hmm... Based on the error that is reported in the CC link, the code he was executing is using the `pymbar.py` included in `simulation-health-reports` which is an old version from SVN control (rev 87 - Tue, 03 Nov 2009, if the `__version__` is to be believed). I think he might have been using the old file, instead of the pymbar-3.0.0-beta2 from conda, although I don't know why installing an older version would have fixed it.

**Comment by jchodera** [comment]
Whoops, good catch!  Let me get rid of that file.

**Comment by Lnaden** [comment]
Closing this as it has probably been resolved.
