### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#231]
Can someone fix this?
https://travis-ci.org/choderalab/pymbar/jobs/141711396#L815-L825

**Comment by Lnaden** [comment]
Those look like failures from the test calls expecting 2 outputs but getting 3. 

This is related to Theta_ij output. We should decide how many outputs we want and keep it that way going forward. May want to open another issue for this and just fix the errors for the time being.

On my phone right now but I can look at this tonight.

**Comment by jchodera** [comment]
I think we want to not return `Theta_ij` unless someone asks for it---I think @mrshirts had made part of that change already?

**Comment by Lnaden** [comment]
Right, but that also means we have a variable number of returns. I had made the change in the #227 code to just `None` the `Theta_ij` if it eas not requested, even if was computed for `dDeltaf_ij`. That way the number of returned variables was constant.

#227 was never merged as AppVoyer tests errored due to what looked like a Windows derp more than a code error. I think merging #227 might stop the errors.

**Comment by jchodera** [comment]
Sorry about that!  See comment in #227.

**Comment by Lnaden** [comment]
I've restarted the the tests from #230 to see if the merged #227 fixes the crashing tests.

**Comment by Lnaden** [comment]
Looks like the tests are passing now, closing.
