### ISSUE TITLE
Enthalpy from MBAR from QM/MM (umbrella sampling)

### ISSUE THREAD

**Issue by sriahisa** [choderalab/pymbar#322]
I am simulating a ligand (4 atoms) transfer  between donor and acceptor using QM/MM (with ~ 20 ps trajectory/window) and umbrella sampling (29 windows). I use the difference in distances as my reaction coordinate (xi= d_xA-d_xD).
The calculated PMF looks smooth and in perfect agreement with WHAM. However, Enthalpy profile is rough and has peaks in the unexpected regions. Can you help me figure out what causes these  unexpected peaks in the enthalpy profile? 
Attached is the time series and my script.

[qmmm_us.zip](https://github.com/choderalab/pymbar/files/4072491/qmmm_us.zip)

Regards,
Saleh

**Comment by mrshirts** [comment]
Can you explain more what quantity you are trying to calculating mathematically? "Enthalpy profile" is a bit vague.   

Generally, ensemble averages are statistically less accurate  than free energies. Do you have uncertainty estimates (perhaps by bootstrapping) that shows you if the peaks are or are not just because of statistical uncertainty?)  You say free energies are very similar to WHAM - do you have a comparison to WHAM of the quantity you are calculating?

**Comment by sriahisa** [comment]
Thanks for your message, Michael.
I like to obtain enthalpy as a function my reaction coordinate.
Since I am doing QM/MM my data is highly correlated (due to very short simulation) so I cannot obtain the uncertainties from  bootstrapping or MBAR. I have a rough estimate of uncertainties  from dividing the trajectories in smaller chunks and averaging PMF among them. Attached is comparison between wham and mbar plus the PMF with error bars.
[enthalpy_wham_vs_mbar.pdf](https://github.com/choderalab/pymbar/files/4073130/enthalpy_wham_vs_mbar.pdf)
[fes_wham_vs_mbar.pdf](https://github.com/choderalab/pymbar/files/4073131/fes_wham_vs_mbar.pdf)
[fes_wham_werrorbars.pdf](https://github.com/choderalab/pymbar/files/4073132/fes_wham_werrorbars.pdf)

**Comment by mrshirts** [comment]
In my mind, the enthalpy of wham vs mbar looks reasonable for small amounts of data.  Enthalpy is generally always noisier than free energy, and the free energy is somewhat noisy. 

> Since I am doing QM/MM my data is highly correlated (due to very short simulation) so I cannot obtain the uncertainties from bootstrapping or MBAR

You can subsample the timeseries so that the data is not highly correlated.  If it is too short to subsample (contains <= 1 correlation time), then it's not clear one can interpret the data in a meaningful way as a statistical sample.

**Comment by mrshirts** [comment]
WHAM has trouble too, and it tends to artificially smooth data out a fair amount by virtue of the histograms, so if WHAM is very spiky, it's likely MBAR will be even more so.

**Comment by sriahisa** [comment]
I understand. Thank you vey much for your help.
