### ISSUE TITLE
If all the temperatures are same in the system, do we just need to apply biased energy to get PMF? 

### ISSUE THREAD

**Issue by qianchen-liu-71** [choderalab/pymbar#401]
From the pymbar/umbrella-sampling-pmf/umbrella-sampling.py file, it says that "# if all the temperatures are the same, then we don't have to read in energies". I was wondering that if all temperatures are same, what should we put into "mbar = pymbar.MBAR(u_kln, N_k, verbose = True)" and results = mbar.computePMF(u_kn, bin_kn, nbins, return_dict=True) in final part? Thank you!

**Comment by mrshirts** [comment]
If all the temperatures are the same, then the energy of the system _other_than_the_biases_ cancels out.  So we don't have to read out the total energy of the system, only recalculate the energies of the biases, which is only a function of the collective variable (here, the torsion angle). So only the energy due to the biases goes into the u_kln (i.e. for each sample from each of the K states, one computes the bias potential of the other states on that sample, for a total of k x k x (number of samples per state) biasing energies.

**Comment by qianchen-liu-71** [comment]
> If all the temperatures are the same, then the energy of the system _other_than_the_biases_ cancels out. So we don't have to read out the total energy of the system, only recalculate the energies of the biases, which is only a function of the collective variable (here, the torsion angle). So only the energy due to the biases goes into the u_kln (i.e. for each sample from each of the K states, one computes the bias potential of the other states on that sample, for a total of k x k x (number of samples per state) biasing energies.

Thank you for your help! That make sense.
